include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  #strong-mode:
  #  implicit-casts: false
  errors:
    unrelated_type_equality_checks: error
    dead_code: info
    empty_statements: error
    avoid_empty_else: error
    unnecessary_statements: error
    unsafe_html: error
    inference_failure_on_function_invocation: ignore

linter:
  rules:
    - unrelated_type_equality_checks
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - avoid_void_async
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - exhaustive_cases
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - non_constant_identifier_names
    - prefer_adjacent_string_concatenation
    - prefer_const_constructors_in_immutables
    #- prefer_expression_function_bodies  # lots of unnecessary lints in build functions
    - prefer_final_locals
    - prefer_final_in_for_each
    #- prefer_int_literals # generates errors in fold()
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - prefer_typing_uninitialized_variables
    - sort_constructors_first
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_is_even_rather_than_modulo
    #- prefer_const_constructors  # lots of unnecessary lints in controllers/services
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_extensions
    - require_trailing_commas
    - file_names
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_if_null_operators
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - curly_braces_in_flow_control_structures
    - empty_constructor_bodies
    - library_names