name: purple_lints
description: Purplesoft commonly used set of lints.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.10.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_code_metrics: 