name: purple_lints
description: Purplesoft commonly used set of lints.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.9.0+2

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_code_metrics: 